# Used to determine which language file to use.
language: "english"

# The list of available maps to play.
map-list:
  - "canyon"
  - "forest_hills"
  - "cavern"
  - "random"

# The name of the random option in the maps list.
random-map: "random"

# The name of the map to use as the lobby
lobby-map: "world"

# The name of the world folder used to store the playing map while a game is in progress.
# This folder will be deleted when a game finishes.
playing-map: "playing"

# The number of teams in colony wars games.
# Team order: red, blue, green, yellow, orange, light_blue, lime, purple, magenta, cyan, silver, brown, black,
# white, gray, pink
team-count: 4

# When to force showdown start
force-showdown:
# The start time is the time after the start if no players are attacked. The attack time is the time after the last
# player was attacked
  times:
    start: 1800
    attack: 300
# The maximum number of teams left that will cause showdown to start
  teams: 2
# The maximum number of players left that will cause showdown to start
  players: 4

# Building info such as schematic locations and default rotations.
buildings:
  schematics:
    Base: "mccw_base.schematic"
    Farm: "mccw_farm.schematic"
    Lumbermill: "mccw_lumbermill.schematic"
    Blacksmith: "mccw_blacksmith.schematic"
    MageTower: "mccw_magetower.schematic"
    Church: "mccw_church.schematic"
    Cathedral: "mccw_cathedral.schematic"
    PlayerCathedral: "mccw_cathedral.schematic"
    Greenhouse: "mccw_greenhouse.schematic"
    ScoutTower: "mccw_scouttower.schematic"
    CannonTower: "mccw_cannontower.schematic"
    Wall: "mccw_wall.schematic"
    Landmine: "mccw_mine.schematic"
    WirelessBuffer: "mccw_rodtrap.schematic"
    TimerBuffer: "mccw_timetrap.schematic"
  rotations:
    Base: 0
    Farm: 0
    Lumbermill: 0
    Blacksmith: 3
    MageTower: 2
    Church: 3
    #Cathedral should always be 0 so that it is built in the same rotation as the church
    Cathedral: 0
    PlayerCathedral: 3
    Greenhouse: 3
    ScoutTower: 2
    CannonTower: 0
    Wall: 0
    Landmine: 0
    WirelessBuffer: 0
    TimerBuffer: 0
  offsets:
    PlayerCathedral:
      x: 0
      y: 1
      z: 0
  transform:
    PlayerCathedral: "Cathedral"

# Costs for all buyables
costs:
  buildings:
    Farm: 2000
    Lumbermill: 2000
    Blacksmith: 4000
    MageTower: 4000
    Church: 4000
    Cathedral: 8000
    Greenhouse: 2000
    Wall: 100
    Landmine: 200
    ScoutTower: 2000
    CannonTower: 2000
    WirelessBuffer: 2500
    TimerBuffer: 2500
  Farm:
    rawPotato: 3
    cookie: 2
    rawBeef: 6
    bakedPotato: 6
    cookedBeef: 10
    goldenApple: 125
  Church:
    healingPotion32: 1250
  Cathedral:
    healingPotion32: 500
    team-compass: 1000
  Greenhouse:
    axe: 1600
  scout:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
    compass1: 400
    regen1: 1600
  general:
    sword1: 1350
    sword2: 1600
  cloaker:
    cloak1: 1350
    cloak2: 1600
  archer:
    sword1: 1350
    sword2: 1600
    bow1: 1350
    bow2: 1600
    arrows1: 1350
    arrows2: 1600
  mage:
    lightning1: 1350
    lightning2: 1600
    ender1: 1350
    ender2: 1600
    healing: 1350
    harming: 400
  peasant:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
  inferno:
    wand1: 1350
    wand2: 1600
    flame1: 1600
    flame2: 1600
    tnt: 75
  dark_knight:
    sword1: 1350
    sword2: 1600
  priest:
    bender1: 1350
    bender2: 1600
    cross1: 1350
    cross2: 1600
    healing1: 1350
    healing2: 1600
  warrior:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
    wolf1: 750
    wolf2: 1000

# The amounts of an item sold (currently only for the farm shop)
amounts:
  Farm:
    rawPotato: 5
    cookie: 10
    rawBeef: 5
    bakedPotato: 10
    cookedBeef: 10
    goldenApple: 1