
buildings:
  schematics:
    Base: "mccw_base.schematic"
    Farm: "mccw_farm.schematic"
    Lumbermill: "mccw_lumbermill.schematic"
    Blacksmith: "mccw_blacksmith.schematic"
    MageTower: "mccw_magetower.schematic"
    Church: "mccw_church.schematic"
    Cathedral: "mccw_cathedral.schematic"
    Greenhouse: "mccw_greenhouse.schematic"
  rotations:
    Base: 0
    Farm: 0
    Lumbermill: 0
    Blacksmith: 3
    MageTower: 2
    Church: 3
    #Cathedral should always be 0 so that it is built in the same rotation as the church
    Cathedral: 0
    Greenhouse: 3

costs:
  buildings:
    Farm: 2000
    Lumbermill: 2000
    Blacksmith: 4000
    MageTower: 4000
    Church: 4000
    Cathedral: 8000
    Greenhouse: 2000
  farm:
    rawPotato: 3
    cookie: 2
    rawBeef: 6
    bakedPotato: 6
    cookedBeef: 10
    goldenApple: 125
  church:
    healingPotion32: 1250
  cathedral:
    healingPotion32: 500
  scout:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
    compass: 400
    regen: 1600
  general:
    sword1: 1350
    sword2: 1600
  cloaker:
    cloak1: 1350
    cloak2: 1600

amounts:
  farm:
    rawPotato: 5
    cookie: 10
    rawBeef: 5
    bakedPotato: 10
    cookedBeef: 10
    goldenApple: 1