# The map that will be loaded by new GameGroups
start_map: "lobby"

maps:

# The language files that will be used by default
lang_files:
  - "english.lang"
  - "lang/items.lang"

custom_items:
  map_voter:
    display_name
  darkness_sword:
    display_name_locale: "darkness_sword.name"
    description_locale: "darkness_sword.desc"
    material: "IRON_HELMET"
    listeners:
      weapon:
        events: ["attack"]
        class: "com.ithinkrok.minigames.item.WeaponModifier"
        config:
          damage: "array(sword, 1, 2.5, 4)"
          effects:
            wither:
              duration: "array(sword, 3, 6, 10)"
            confusion:
              duration: "array(sword, 5, 7, 8)"
      lightning:
        events: ["attack", "rightClick"]
        class: "com.ithinkrok.cw.item.LightningWand"
        config:
          max_range: 100
          damage_multiplier: 2.8