
maps:
  canyon:
    folder: "canyon"
    center:
      x: -178
      y: 95
      z: 183
    showdown-size:
      x: 30
      z: 30
    red:
      base:
        x: -363
        y: 94
        z: -3
      spawn:
        x: -362
        y: 94
        z: -2
    blue:
      base:
        x: 9
        y: 94
        z: -2
      spawn:
        x: 8
        y: 94
        z: -1
    green:
      base:
        x: 8
        y: 94
        z: 370
      spawn:
        x: 7
        y: 64
        z: 369
    yellow:
      base:
        x: -364
        y: 94
        z: 369
      spawn:
        x: -363
        y: 94
        z: 368

buildings:
  schematics:
    Base: "mccw_base.schematic"
    Farm: "mccw_farm.schematic"
    Lumbermill: "mccw_lumbermill.schematic"
    Blacksmith: "mccw_blacksmith.schematic"
    MageTower: "mccw_magetower.schematic"
    Church: "mccw_church.schematic"
    Cathedral: "mccw_cathedral.schematic"
    Greenhouse: "mccw_greenhouse.schematic"
  rotations:
    Base: 0
    Farm: 0
    Lumbermill: 0
    Blacksmith: 3
    MageTower: 2
    Church: 3
    #Cathedral should always be 0 so that it is built in the same rotation as the church
    Cathedral: 0
    Greenhouse: 3

costs:
  buildings:
    Farm: 2000
    Lumbermill: 2000
    Blacksmith: 4000
    MageTower: 4000
    Church: 4000
    Cathedral: 8000
    Greenhouse: 2000
  farm:
    rawPotato: 3
    cookie: 2
    rawBeef: 6
    bakedPotato: 6
    cookedBeef: 10
    goldenApple: 125
  church:
    healingPotion32: 1250
  cathedral:
    healingPotion32: 500
  greenhouse:
    axe: 1600
  scout:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
    compass: 400
    regen: 1600
  general:
    sword1: 1350
    sword2: 1600
  cloaker:
    cloak1: 1350
    cloak2: 1600
  archer:
    sword1: 1350
    sword2: 1600
    bow1: 1350
    bow2: 1600
    arrows1: 1350
    arrows2: 1600
  mage:
    lightning1: 1350
    lightning2: 1600
    ender1: 1350
    ender2: 1600
    healing: 1350
    harming: 400

amounts:
  farm:
    rawPotato: 5
    cookie: 10
    rawBeef: 5
    bakedPotato: 10
    cookedBeef: 10
    goldenApple: 1

locale:
  class-chooser: "Class Chooser"
  general-desc: "Fights with a diamond sword"
  scout-desc: "Runs fast and has a player locator"
  archer-desc: "Fights with a bow!"
  cloaker-desc: "Can go invisible for short periods of time"
  mage-desc: "Can strike lightning and use harming potions"
  team-chooser: "Team Chooser"
  team-desc: "%s Team"
  team-already-member: "§cYou are already in the %s §cTeam"
  team-full: "§cThe %s §cTeam is full. Try another"
  team-joined: "§6You will be in the %s §6Team in the next game!"
  class-selected: "§6You will be a %s §6in the next game!"
  team-chooser-desc: "Choose your team"
  class-chooser-desc: "Choose your class"
  choose-team-class: "§2Choose your team/class or it is chosen randomly"
  map-info: "§2Canyon is the only map so there is no map voting"
  start-minute-warning: "§7Game starting in§6 %s §7Minutes.."
  start-seconds-warning: "§7Game starting in§6 %s §7Seconds.."
  start-final-warning: "§6%s§7!"
  showdown-minute-warning: "§6§lShowdown starts in: %s minutes!"
  showdown-seconds-warning: "§6§lShowdown starts in: %s seconds!"
  showdown-final-warning: "§6§lShowdown starts in: %s seconds!"
  end-minute-warning: "§e§lGame ending in§c§l %s minutes!"
  end-seconds-warning: "§e§lGame ending in§c§l %s seconds!"
  end-final-warning: "§e§lGame ending in§c§l %s seconds!"
  player-join-game: "%s §7joined the server §8[§7%s§8/§7%s§8]"
  player-quit-game: "%s §7left the server §8[§7%s§8/§7%s§8]"
  not-enough-players: "§7Not enough Players Online for Game to start!"
  game-in-progress: "§4There is already a game in progress!"
  game-wait-next: "§6You can play when the current game ends"
  spectate-heads: "§6Choose a player to spectate from your inventory"
  spectate-player: "§dSpectate %s"
  building-shop: "§a%s Shop"
  click-to-open: "§f§oClick to Open"
  obsidian-not-building: "§cThat obsidian block does not appear to be a shop."
  building-not-yours: "§eThat building does not belong to your team. §lMine this block to destroy it!"
  building-not-finished: "§cPlease wait until the construction has finished."
  ender-wand-cooldown: "§cThe ender wand is cooling down."
  lightning-wand-cooldown: "§cThe lightning wand is cooling down."