map-list:
  - "canyon"
  - "forest_hills"
  - "random"

random-map: "random"

maps:
  canyon:
    folder: "canyon"
    center:
      x: -178
      y: 95
      z: 183
    showdown-size:
      x: 30
      z: 30
    red:
      base:
        x: -363
        y: 94
        z: -3
      spawn:
        x: -362
        y: 94
        z: -2
    blue:
      base:
        x: 9
        y: 94
        z: -2
      spawn:
        x: 8
        y: 94
        z: -1
    green:
      base:
        x: 8
        y: 94
        z: 370
      spawn:
        x: 7
        y: 64
        z: 369
    yellow:
      base:
        x: -364
        y: 94
        z: 369
      spawn:
        x: -363
        y: 94
        z: 368
  forest_hills:
    folder: "forest_hills"
    center:
      x: -227
      y: 28
      z: -242
    showdown-size:
      x: 30
      z: 30
    red:
      base:
        x: -29
        y: 25
        z: -44
      spawn:
        x: -30
        y: 25
        z: -45
    yellow:
      base:
        x: -425
        y: 25
        z: -44
      spawn:
        x: -424
        y: 25
        z: -45
    green:
      base:
        x: -425
        y: 25
        z: -440
      spawn:
        x: -424
        y: 25
        z: -439
    blue:
      base:
        x: -29
        y: 25
        z: -440
      spawn:
        x: -30
        y: 25
        z: -439

buildings:
  schematics:
    Base: "mccw_base.schematic"
    Farm: "mccw_farm.schematic"
    Lumbermill: "mccw_lumbermill.schematic"
    Blacksmith: "mccw_blacksmith.schematic"
    MageTower: "mccw_magetower.schematic"
    Church: "mccw_church.schematic"
    Cathedral: "mccw_cathedral.schematic"
    PlayerCathedral: "mccw_cathedral.schematic"
    Greenhouse: "mccw_greenhouse.schematic"
    ScoutTower: "mccw_scouttower.schematic"
    CannonTower: "mccw_cannontower.schematic"
    Wall: "mccw_wall.schematic"
    Landmine: "mccw_mine.schematic"
    WirelessBuffer: "mccw_rodtrap.schematic"
    TimerBuffer: "mccw_timetrap.schematic"
  rotations:
    Base: 0
    Farm: 0
    Lumbermill: 0
    Blacksmith: 3
    MageTower: 2
    Church: 3
    #Cathedral should always be 0 so that it is built in the same rotation as the church
    Cathedral: 0
    PlayerCathedral: 3
    Greenhouse: 3
    ScoutTower: 2
    CannonTower: 2
    Wall: 0
    Landmine: 0
    WirelessBuffer: 0
    TimerBuffer: 0
  offsets:
    PlayerCathedral:
      x: 0
      y: 1
      z: 0
  transform:
    PlayerCathedral: "Cathedral"

costs:
  buildings:
    Farm: 2000
    Lumbermill: 2000
    Blacksmith: 4000
    MageTower: 4000
    Church: 4000
    Cathedral: 8000
    Greenhouse: 2000
    Wall: 100
    Landmine: 200
    ScoutTower: 2000
    CannonTower: 2000
    WirelessBuffer: 2500
    TimerBuffer: 2500
  farm:
    rawPotato: 3
    cookie: 2
    rawBeef: 6
    bakedPotato: 6
    cookedBeef: 10
    goldenApple: 125
  church:
    healingPotion32: 1250
  cathedral:
    healingPotion32: 500
  greenhouse:
    axe: 1600
  scout:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
    compass: 400
    regen: 1600
  general:
    sword1: 1350
    sword2: 1600
  cloaker:
    cloak1: 1350
    cloak2: 1600
  archer:
    sword1: 1350
    sword2: 1600
    bow1: 1350
    bow2: 1600
    arrows1: 1350
    arrows2: 1600
  mage:
    lightning1: 1350
    lightning2: 1600
    ender1: 1350
    ender2: 1600
    healing: 1350
    harming: 400
  peasant:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
  inferno:
    wand1: 1350
    wand2: 1600
    flame1: 1600
    flame2: 1600
    tnt: 75
  dark_knight:
    sword1: 1350
    sword2: 1600
  priest:
    bender1: 1350
    bender2: 1600
    cross1: 1350
    cross2: 1600
    healing1: 1350
    healing2: 1600

amounts:
  farm:
    rawPotato: 5
    cookie: 10
    rawBeef: 5
    bakedPotato: 10
    cookedBeef: 10
    goldenApple: 1

locale:
  map-chooser: "Map Voter"
  map-chooser-desc: "Vote for a map"
  canyon-desc: "A canyon seperates the four teams bases..."
  forest_hills-desc: "Teams separated by forest and hills."
  random-desc: "Vote for a random map"
  class-chooser: "Class Chooser"
  general-desc: "Fights with a diamond sword"
  scout-desc: "Runs fast and has a player locator"
  archer-desc: "Fights with a bow!"
  cloaker-desc: "Can go invisible for short periods of time"
  mage-desc: "Can strike lightning and use harming potions"
  peasant-desc: "Has an enchanted iron axe to get money faster"
  inferno-desc: "Has an explosion wand and TNT"
  dark_knight-desc: "Wields the darkness sword..."
  team-chooser: "Team Chooser"
  team-desc: "%s Team"
  team-already-member: "§cYou are already in the %s §cTeam"
  team-full: "§cThe %s §cTeam is full. Try another"
  team-joined: "§6You will be in the %s §6Team in the next game!"
  class-selected: "§6You will be a %s §6in the next game!"
  team-chooser-desc: "Choose your team"
  class-chooser-desc: "Choose your class"
  choose-team-class: "§2Choose your team/class or it is chosen randomly"
  map-info: "§2Map voting is now available!"
  start-minute-warning: "§7Game starting in§6 %s §7Minutes.."
  start-seconds-warning: "§7Game starting in§6 %s §7Seconds.."
  start-final-warning: "§6%s§7!"
  showdown-minute-warning: "§6§lShowdown starts in: %s minutes!"
  showdown-seconds-warning: "§6§lShowdown starts in: %s seconds!"
  showdown-final-warning: "§6§lShowdown starts in: %s seconds!"
  end-minute-warning: "§e§lGame ending in§c§l %s minutes!"
  end-seconds-warning: "§e§lGame ending in§c§l %s seconds!"
  end-final-warning: "§e§lGame ending in§c§l %s seconds!"
  player-join-game: "%s §7joined the server §8[§7%s§8/§7%s§8]"
  player-quit-game: "%s §7left the server §8[§7%s§8/§7%s§8]"
  not-enough-players: "§7Not enough Players Online for Game to start!"
  game-in-progress: "§4There is already a game in progress!"
  game-wait-next: "§6You can play when the current game ends"
  spectate-heads: "§6Choose a player to spectate from your inventory"
  spectate-player: "§dSpectate %s"
  building-shop: "§a%s Shop"
  click-to-open: "§f§oClick to Open"
  obsidian-not-building: "§cThat obsidian block does not appear to be a shop."
  building-not-yours: "§eThat building does not belong to your team. §lMine this block to destroy it!"
  building-not-finished: "§cPlease wait until the construction has finished."
  ender-wand-cooldown: "§aThe ender wand is ready to use again."
  lightning-wand-cooldown: "§aThe lightning wand is ready to use again."
  explosion-wand-cooldown: "§aThe explosion wand is ready to use again."
  map-voted: "§6You have voted for §3%s§6!"
  map-already-voted: "§cYou already voted for §3%s§c!"
  player-voted: "§6%s §6voted for §3%s§3!"
  player-vote-change: "§6%s §6changed their vote from §3%s§6 to §3%s§6!"
  map-chosen: "§6Playing map: §3%s"
  player-killed-player: "§6%s §6was killed by %s"
  player-died-last-attacker: "§6%s §6died while fighting %s§6!"
  player-died: "§6%s §6died!"