# The map that will be loaded by new GameGroups
start_map: "lobby"

# The language files that will be used by default
lang_files:
  - "colony_wars.lang"
  - "lang/weapon_modifier.lang"
  - "lang/items.lang"
  - "lang/commands.lang"

# Specifies identifiers for teams to be created
team_identifiers:
  red:
    dye_color: RED
  blue:
    dye_color: BLUE
  green:
    dye_color: GREEN
  yellow:
    dye_color: YELLOW

kits:
  general:
    listeners: {}
#TODO kits and KitChangeEvent

schematics:
  Base:
    file: "schematics/mccw_base.schematic"
    rotation: 0
    upgrades:
      - "Fortress"
    config:
      base: true
      protected: true
      shop:
        - class: "com.ithinkrok.cw.inventory.BuildingBuyable"
          config:
            building_name: "Farm"
            cost: 2000
            team: true
        - class: "com.ithinkrok.cw.inventory.BuildingBuyableWith"
          config:
            building_name: "Lumbermill"
            cost: 2000
            team: true
            with_buildings:
              - "Farm"
        - class: "com.ithinkrok.cw.inventory.BuildingBuyableWith"
          config:
            building_name: "Blacksmith"
            cost: 4000
            team: true
            with_buildings:
              - "Farm"
        - class: "com.ithinkrok.cw.inventory.BuildingBuyableWith"
          config:
            building_name: "MageTower"
            cost: 4000
            team: true
            with_buildings:
              - "Farm"
        - class: "com.ithinkrok.cw.inventory.BuildingBuyableWith"
          config:
            building_name: "Church"
            cost: 4000
            team: true
            with_buildings:
              - "Farm"
        - class: "com.ithinkrok.cw.inventory.BuildingBuyableWith"
          config:
            building_name: "Greenhouse"
            cost: 2000
            team: true
            with_buildings:
              - "Farm"
  Fortress:
    file: "schematics/mccw_fortress.schematic"
    rotation: 0
    config:
      base: true
      cannons: true
      protected: true
  Farm:
    file: "schematics/mccw_farm.schematic"
    rotation: 0
  Lumbermill:
    file: "schematics/mccw_lumbermill.schematic"
    rotation: 0
  Blacksmith:
    file: "schematics/mccw_blacksmith.schematic"
    rotation: 3
  MageTower:
    file: "schematics/mccw_magetower.schematic"
    rotation: 2
  Church:
    file: "schematics/mccw_church.schematic"
    rotation: 3
    upgrades:
      - "Cathedral"
    config:
      shop:
        - class: "com.ithinkrok.cw.inventory.BuildingUpgrade"
          config:
            building_name: "Cathedral"
            cost: 8000
            team: true
    config:
      revival_rate: 30
  Cathedral:
    file: "schematics/mccw_cathedral.schematic"
    rotation: 3
    config:
      revival_rate: 75
  Greenhouse:
    file: "schematics/mccw_greenhouse.schematic"
    rotation: 3
  ScoutTower:
    file: "schematics/mccw_scouttower.schematic"
    rotation: 2
    upgrades:
      - "CannonTower"
  CannonTower:
    file: "schematics/mccw_cannontower.schematic"
    rotation: 2
    config:
      cannons: true
  Wall:
    file: "schematics/mccw_wall.schematic"
    rotation: 0
  Landmine:
    file: "schematics/mccw_mine.schematic"
    rotation: 0

# Specifies default shared objects. Some shared objects are required by certain Java Classes used in the game.
shared_objects:
  gold_config:
    ore_blocks:
      gold_ore: "GOLD_INGOT,6"
      quartz_ore: "GOLD_INGOT,6"
      diamond_ore: "DIAMOND,1"
    trees:
      enabled: true
      item_material: "GOLD_INGOT"
      item_amount: "1+x+(ln(x)/ln(1.5))-min(sqrt((x^3)/500),x^0.9)"
      log_materials:
        - "LOG"
        - "LOG_2"
    items:
      gold_ingot:
        user: 60
        team: 40
      diamond:
        user: 1200
        team: 800
    pickup_sound: "ORB_PICKUP"
  # Required for UserMoney.java
  user_money_metadata:
    remove_gamestate: "aftermath"
    add_locale: "money.balance.user.add"
    subtract_locale: "money.balance.user.subtract"
    new_locale: "money.balance.user.new"
  # Required for TeamMoney.java
  team_money_metadata:
    remove_gamestate: "aftermath"
    add_locale: "money.balance.team.add"
    subtract_locale: "money.balance.team.subtract"
    new_locale: "money.balance.team.new"
  # Required for CWScoreboardHandler.java
  colony_wars_scoreboard:
    title: "scoreboard.title"
    user_balance: "scoreboard.user_balance"
    team_balance: "scoreboard.team_balance"
    building_now_count: "scoreboard.building_now_count"
    revival_rate: "scoreboard.revival_rate"
  schematic_options:
    progress_hologram: true
    build_speed: 2
    center_block_material: "OBSIDIAN"
    replace_materials:
      BARRIER: "AIR"
      DIAMOND_ORE: "GOLD_ORE"
# Required for User.java
  user:
    default_stats:
      max_health: 20
      health: 20
      food_level: 10
      saturation: 5
      fly_speed: 0.1
      walk_speed: 0.2

game_states:
  lobby:
    listeners:
      main:
        class: "com.ithinkrok.cw.gamestate.LobbyListener"
        config:
          start_countdown:
            name: "start"
            locale_stub: "countdowns.start"
            min_players: 1
            needs_more_players_locale: "countdowns.start.needs_more_players"
            seconds: 181

          next_gamestate: "game"
          lobby_map: "lobby"
  game:
    listeners:
      main:
        class: "com.ithinkrok.cw.gamestate.GameListener"
        config:
          gold_shared_object: "gold_config"
          buildings:
            destroy_wait: 3
          map_voting:
            random_map: "random"
            map_list: &votable_maps
              - "canyon"
#              - "forest_hills"
#              - "cavern"
              - "random"
          choosable_teams: &choosable_teams
            - "red"
            - "blue"
            - "green"
            - "yellow"
          choosable_kits:
            - "general"
          start_items:
            clear_inventory: true
            items:
              - name: "pickaxe"
                slot: 0
start_game_state: "lobby"

custom_items:
  map_voter:
    display_name_locale: "map_voter.name"
    description_locale: "map.voter.desc"
    material: "EMPTY_MAP"
    listeners:
      vote:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.inventory.MapVoter"
        config:
          votable_maps: *votable_maps
          map_material: "EMPTY_MAP"
  team_chooser:
    display_name_locale: "team_chooser.name"
    description_locale: "team_chooser.desc"
    material: "LEATHER_HELMET"
    listeners:
      choose:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.inventory.TeamChooser"
        config:
          choosable_teams: *choosable_teams
          chooser_material: "WOOL"
  class_chooser:
    display_name_locale: "kit_chooser.name"
    description_locale: "kit_chooser.desc"
    material: "WOOD_SWORD"
    listeners:
      choose:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.inventory.KitChooser"
        config:
          choosable_kits:
            general: "DIAMOND_SWORD,1,0,General"
  darkness_sword:
    display_name_locale: "darkness_sword.name"
    description_locale: "darkness_sword.desc"
    material: "IRON_HELMET"
    listeners:
      weapon:
        events: ["attack"]
        class: "com.ithinkrok.minigames.item.WeaponModifier"
        config:
          damage: "array(sword, 1, 2.5, 4)"
          effects:
            wither:
              duration: "array(sword, 3, 6, 10)"
            confusion:
              duration: "array(sword, 5, 7, 8)"
      lightning:
        events: ["attack", "rightClick"]
        class: "com.ithinkrok.cw.item.LightningWand"
        config:
          max_range: 100
          damage_multiplier: 2.8
  pickaxe:
    material: "DIAMOND_PICKAXE"
listeners:
  give_on_join:
    class: "com.ithinkrok.minigames.listener.GiveCustomItemsOnJoin"
    config:
      clear_inventory: true
      items:
        - name: "map_voter"
          slot: 0
        - name: "team_chooser"
          slot: 1
        - name: "class_chooser"
          slot: 2