# The map that will be loaded by new GameGroups
start_map: "lobby"

# The language files that will be used by default
lang_files:
  - "colony_wars.lang"
  - "lang/weapon_modifier.lang"
  - "lang/items.lang"

game_states:
  lobby:
    listeners:
      main:
        class: "com.ithinkrok.cw.gamestate.LobbyListener"
        config:
          start_countdown:
            name: "start"
            locale_stub: "countdowns.start"
            min_players: 1
            needs_more_players_locale: "countdowns.start.needs_more_players"
            seconds: 20
          map_voting:
            random_map: "random"
            map_list: &votable_maps
              - "canyon"
              - "forest_hills"
              - "cavern"
              - "random"
          next_gamestate: "game"
  game:
    listeners:
      main:
        class: "com.ithinkrok.cw.gamestate.GameListener"

start_game_state: "lobby"

custom_items:
  map_voter:
    display_name_locale: "map_voter.name"
    description_locale: "map.voter.desc"
    material: "EMPTY_MAP"
    listeners:
      vote:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.item.MapVoter"
        config:
          votable_maps: *votable_maps
          map_material: "EMPTY_MAP"
  darkness_sword:
    display_name_locale: "darkness_sword.name"
    description_locale: "darkness_sword.desc"
    material: "IRON_HELMET"
    listeners:
      weapon:
        events: ["attack"]
        class: "com.ithinkrok.minigames.item.WeaponModifier"
        config:
          damage: "array(sword, 1, 2.5, 4)"
          effects:
            wither:
              duration: "array(sword, 3, 6, 10)"
            confusion:
              duration: "array(sword, 5, 7, 8)"
      lightning:
        events: ["attack", "rightClick"]
        class: "com.ithinkrok.cw.item.LightningWand"
        config:
          max_range: 100
          damage_multiplier: 2.8

listeners:
  give_on_join:
    class: "com.ithinkrok.minigames.listener.GiveCustomItemsOnJoin"
    config:
      clear_inventory: true
      items:
        - name: "map_voter"
          slot: 0
        - name: "darkness_sword"
          slot: 1