# The map that will be loaded by new GameGroups
start_map: "lobby"

# The language files that will be used by default
lang_files:
  - "colony_wars.lang"
  - "lang/weapon_modifier.lang"
  - "lang/items.lang"

# Specifies default shared objects. Some shared objects are required by certain Java Classes used in the game.
shared_objects:
  gold_config:
    ore_blocks:
      gold_ore: "GOLD_INGOT,6"
      quartz_ore: "GOLD_INGOT,6"
      diamond_ore: "DIAMOND,1"
    trees:
      enabled: true
      item_material: "GOLD_INGOT"
      item_amount: "1+x+(ln(x)/ln(1.5))-min(sqrt((x^3)/500),x^0.9)"
      log_materials:
        - "LOG"
        - "LOG_2"
    items:
      gold_ingot:
        user: 60
        team: 40
      diamond:
        user: 1200
        team: 800
  # Required for UserMoney.java
  user_money_metadata:
    remove_gamestate: "aftermath"
    add_locale: "money.balance.user.add"
    subtract_locale: "money.balance.user.subtract"
    new_locale: "money.balance.user.new"

game_states:
  lobby:
    listeners:
      main:
        class: "com.ithinkrok.cw.gamestate.LobbyListener"
        config:
          start_countdown:
            name: "start"
            locale_stub: "countdowns.start"
            min_players: 1
            needs_more_players_locale: "countdowns.start.needs_more_players"
            seconds: 3
          map_voting:
            random_map: "random"
            map_list: &votable_maps
              - "canyon"
#              - "forest_hills"
#              - "cavern"
              - "random"
          next_gamestate: "game"
  game:
    listeners:
      main:
        class: "com.ithinkrok.cw.gamestate.GameListener"
        config:
          gold_shared_object: "gold_config"


start_game_state: "lobby"

custom_items:
  map_voter:
    display_name_locale: "map_voter.name"
    description_locale: "map.voter.desc"
    material: "EMPTY_MAP"
    listeners:
      vote:
        events: ["rightClick"]
        class: "com.ithinkrok.minigames.item.MapVoter"
        config:
          votable_maps: *votable_maps
          map_material: "EMPTY_MAP"
  darkness_sword:
    display_name_locale: "darkness_sword.name"
    description_locale: "darkness_sword.desc"
    material: "IRON_HELMET"
    listeners:
      weapon:
        events: ["attack"]
        class: "com.ithinkrok.minigames.item.WeaponModifier"
        config:
          damage: "array(sword, 1, 2.5, 4)"
          effects:
            wither:
              duration: "array(sword, 3, 6, 10)"
            confusion:
              duration: "array(sword, 5, 7, 8)"
      lightning:
        events: ["attack", "rightClick"]
        class: "com.ithinkrok.cw.item.LightningWand"
        config:
          max_range: 100
          damage_multiplier: 2.8

listeners:
  give_on_join:
    class: "com.ithinkrok.minigames.listener.GiveCustomItemsOnJoin"
    config:
      clear_inventory: true
      items:
        - name: "map_voter"
          slot: 0
        - name: "darkness_sword"
          slot: 1