# The map that will be loaded by new GameGroups
start_map: "lobby"

maps:
  - "lobby"

# The language files that will be used by default
lang_files:
  - "english.lang"
  - "lang/weapon_modifier.lang"
  - "lang/items.lang"

custom_items:
  map_voter:
    display_name_locale: "map_voter.name"
    description_locale: "map.voter.desc"
    material: "EMPTY_MAP"
  darkness_sword:
    display_name_locale: "darkness_sword.name"
    description_locale: "darkness_sword.desc"
    material: "IRON_HELMET"
    listeners:
      weapon:
        events: ["attack"]
        class: "com.ithinkrok.minigames.item.WeaponModifier"
        config:
          damage: "array(sword, 1, 2.5, 4)"
          effects:
            wither:
              duration: "array(sword, 3, 6, 10)"
            confusion:
              duration: "array(sword, 5, 7, 8)"
      lightning:
        events: ["attack", "rightClick"]
        class: "com.ithinkrok.cw.item.LightningWand"
        config:
          max_range: 100
          damage_multiplier: 2.8

listeners:
  give_on_join:
    class: "com.ithinkrok.minigames.listener.GiveCustomItemsOnJoin"
    config:
      clear_inventory: true
      items:
        - name: "map_voter"
          slot: 0
        - name: "darkness_sword"
          slot: 1