# Used to determine which language file to use.
language: "english"

# The list of available maps to play.
map-list:
  - "canyon"
  - "forest_hills"
  - "cavern"
  - "random"

# The name of the random option in the maps list.
random-map: "random"

# The name of the map to use as the lobby
lobby-map: "world"

# The name of the world folder used to store the playing map while a game is in progress.
# This folder will be deleted when a game finishes.
playing-map: "playing"

# The number of teams in colony wars games.
# Team order: red, blue, green, yellow, orange, light_blue, lime, purple, magenta, cyan, silver, brown, black,
# white, gray, pink
team-count: 4

# Map info
maps:
  canyon:
    folder: "canyon"
    center:
      x: -178
      y: 95
      z: 183
    showdown-size:
      x: 30
      z: 30
    red:
      base:
        x: -363
        y: 94
        z: -3
      spawn:
        x: -362
        y: 94
        z: -2
    blue:
      base:
        x: 9
        y: 94
        z: -2
      spawn:
        x: 8
        y: 94
        z: -1
    green:
      base:
        x: 8
        y: 94
        z: 370
      spawn:
        x: 7
        y: 64
        z: 369
    yellow:
      base:
        x: -364
        y: 94
        z: 369
      spawn:
        x: -363
        y: 94
        z: 368
  forest_hills:
    folder: "forest_hills"
    center:
      x: -227
      y: 28
      z: -242
    showdown-size:
      x: 30
      z: 30
    red:
      base:
        x: -29
        y: 25
        z: -44
      spawn:
        x: -30
        y: 25
        z: -45
    yellow:
      base:
        x: -425
        y: 25
        z: -44
      spawn:
        x: -424
        y: 25
        z: -45
    green:
      base:
        x: -425
        y: 25
        z: -440
      spawn:
        x: -424
        y: 25
        z: -439
    blue:
      base:
        x: -29
        y: 25
        z: -440
      spawn:
        x: -30
        y: 25
        z: -439
  cavern:
    folder: "cavern"
    center:
      x: -235
      y: 115
      z: 209
    showdown-size:
      x: 30
      z: 30
    red:
      base:
        x: -451
        y: 134
        z: -7
      spawn:
        x: -450
        y: 135
        z: -6
    orange:
      base:
        x: -312
        y: 111
        z: -9
      spawn:
        x: -313
        y: 112
        z: -8
    magenta:
      base:
        x: -419
        y: 108
        z: 142
      spawn:
        x: -418
        y: 109
        z: 141
    yellow:
      base:
        x: -19
        y: 134
        z: -7
      spawn:
        x: -20
        y: 135
        z: -6
    purple:
      base:
        x: -17
        y: 111
        z: 132
      spawn:
        x: -18
        y: 112
        z: 131
    brown:
      base:
        x: -168
        y: 108
        z: 25
      spawn:
        x: -167
        y: 109
        z: 26
    blue:
      base:
        x: -19
        y: 134
        z: 425
      spawn:
        x: -20
        y: 135
        z: 424
    light_blue:
      base:
        x: -158
        y: 112
        z: 428
      spawn:
        x: -157
        y: 112
        z: 426
    cyan:
      base:
        x: -51
        y: 108
        z: 276
      spawn:
        x: -52
        y: 109
        z: 277
    green:
      base:
        x: -451
        y: 134
        z: 425
      spawn:
        x: -450
        y: 135
        z: 424
    lime:
      base:
        x: -453
        y: 111
        z: 286
      spawn:
        x: -452
        y: 112
        z: 287
    silver:
      base:
        x: -302
        y: 108
        z: 393
      spawn:
        x: -303
        y: 109
        z: 392


# Building info such as schematic locations and default rotations.
buildings:
  schematics:
    Base: "mccw_base.schematic"
    Farm: "mccw_farm.schematic"
    Lumbermill: "mccw_lumbermill.schematic"
    Blacksmith: "mccw_blacksmith.schematic"
    MageTower: "mccw_magetower.schematic"
    Church: "mccw_church.schematic"
    Cathedral: "mccw_cathedral.schematic"
    PlayerCathedral: "mccw_cathedral.schematic"
    Greenhouse: "mccw_greenhouse.schematic"
    ScoutTower: "mccw_scouttower.schematic"
    CannonTower: "mccw_cannontower.schematic"
    Wall: "mccw_wall.schematic"
    Landmine: "mccw_mine.schematic"
    WirelessBuffer: "mccw_rodtrap.schematic"
    TimerBuffer: "mccw_timetrap.schematic"
  rotations:
    Base: 0
    Farm: 0
    Lumbermill: 0
    Blacksmith: 3
    MageTower: 2
    Church: 3
    #Cathedral should always be 0 so that it is built in the same rotation as the church
    Cathedral: 0
    PlayerCathedral: 3
    Greenhouse: 3
    ScoutTower: 2
    CannonTower: 0
    Wall: 0
    Landmine: 0
    WirelessBuffer: 0
    TimerBuffer: 0
  offsets:
    PlayerCathedral:
      x: 0
      y: 1
      z: 0
  transform:
    PlayerCathedral: "Cathedral"

# Costs for all buyables
costs:
  buildings:
    Farm: 2000
    Lumbermill: 2000
    Blacksmith: 4000
    MageTower: 4000
    Church: 4000
    Cathedral: 8000
    Greenhouse: 2000
    Wall: 100
    Landmine: 200
    ScoutTower: 2000
    CannonTower: 2000
    WirelessBuffer: 2500
    TimerBuffer: 2500
  farm:
    rawPotato: 3
    cookie: 2
    rawBeef: 6
    bakedPotato: 6
    cookedBeef: 10
    goldenApple: 125
  church:
    healingPotion32: 1250
  cathedral:
    healingPotion32: 500
    team-compass: 1000
  greenhouse:
    axe: 1600
  scout:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
    compass: 400
    regen: 1600
  general:
    sword1: 1350
    sword2: 1600
  cloaker:
    cloak1: 1350
    cloak2: 1600
  archer:
    sword1: 1350
    sword2: 1600
    bow1: 1350
    bow2: 1600
    arrows1: 1350
    arrows2: 1600
  mage:
    lightning1: 1350
    lightning2: 1600
    ender1: 1350
    ender2: 1600
    healing: 1350
    harming: 400
  peasant:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
  inferno:
    wand1: 1350
    wand2: 1600
    flame1: 1600
    flame2: 1600
    tnt: 75
  dark_knight:
    sword1: 1350
    sword2: 1600
  priest:
    bender1: 1350
    bender2: 1600
    cross1: 1350
    cross2: 1600
    healing1: 1350
    healing2: 1600
  warrior:
    sharpness1: 1350
    sharpness2: 1600
    knockback1: 1350
    knockback2: 1600
    wolf1: 750
    wolf2: 1000

# The amounts of an item sold (currently only for the farm shop)
amounts:
  farm:
    rawPotato: 5
    cookie: 10
    rawBeef: 5
    bakedPotato: 10
    cookedBeef: 10
    goldenApple: 1