name: "ColonyWars"
version: "${project.version}"
main: "com.ithinkrok.cw.CWPlugin"
author: "ithinkrok"
database: true

permissions:
  mccw.admin:
    default: "op"
    description: "Gives all admin command permissions"
    children:
      mccw.gamestate: true
  mccw.gamestate:
    description: "Allows use of the /gamestate command"
    default: false

commands:
  gamestate:
    description: "Changes the GameState of the current GameGroup"
    aliases: ["gs", "gstate"]
    permission: "mccw.gamestate"
    usage: "/<command> <gamestate>"