name: "Colony Wars"
version: "${project.version}"
main: "com.ithinkrok.mccw.WarsPlugin"
author: "ithinkrok"
depend: ["HologramAPI"]
commands:
  transfer:
    description: "Transfers money from your account to your team's account"
    aliases: ["t", "tf"]
    usage: "/transfer [money]"