name: "ColonyWars"
version: "${project.version}"
main: "com.ithinkrok.mccw.WarsPlugin"
author: "ithinkrok"
depend: ["HologramAPI", "ProtocolLib"]
database: true
permissions:
  mccw.*:
    description: "Gives access to all MCCW commands"
    children:
      mccw.test: true
      mccw.gamestate: true
      mccw.members: true
      mccw.spawn: true
      mccw.fix: true
      mccw.countdown: true
      mccw.stats: true
    default: "op"
  mccw.test:
    description: "Allows use of the test command"
  mccw.countdown:
    description: "Allows the use of the countdown command"
  mccw.gamestate:
    description: "Allows use of the gamestate command"
  mccw.members:
    description: "allows use of the members command"
    default: true
  mccw.spawn:
    description: "Allows use of the spawn command"
    default: true
  mccw.fix:
    description: "Allows use of the fix command"
    default: true
  mccw.stats:
    description: "Allows use of the stats command"
    default: true
commands:
  transfer:
    description: "Transfers money from your account to your team's account"
    aliases: ["t", "tf"]
    usage: "/transfer [money]"
  test:
    description: "ColonyWars test command"
    usage: "/test <test> [test arguments...]"
    permission: "mccw.test"
  gamestate:
    description: "Changes the game state"
    aliases: ["gs"]
    usage: "/gamestate <newstate>"
    permission: "mccw.gamestate"
  members:
    description: "Lists the members of your team"
    aliases: ["mbrs", "players", "team", "plrs", "classes"]
    usage: "/members"
    permission: "mccw.members"
  spawn:
    description: "If you are in the lobby, teleports you to the center"
    aliases: ["center"]
    usage: "/spawn"
    permission: "mccw.spawn"
  fix:
    description: "Fixes you if you are stuck"
    aliases: ["fixme", "unstuck"]
    usage: "/fix"
    permission: "mccw.fix"
  countdown:
    description: "Change the countdown time remaining"
    aliases: ["cd", "count","timer"]
    usage: "/countdown <value-to-add>"
    permission: "mccw.countdown"
  stats:
    description: "Gets your stats"
    usage: "/stats [category]"
    permission: "mccw.stats"
