name: "ColonyWars"
version: "${project.version}"
main: "com.ithinkrok.cw.CWPlugin"
author: "ithinkrok"
depend: ["HologramAPI", "ProtocolLib"]
softdepend: ["DisguiseCraft"]
database: true

permissions:
  mccw.admin:
    default: "op"
    description: "Gives all admin command permissions"
    children:
      mccw.gamestate: true
      mccw.cw: true
      mccw.tmm.others: true
      mccw.countdown: true
  mccw.user:
    default: true
    description: "Gives all user command permission"
    children:
      mccw.tmm: true
      mccw.stats: true
  mccw.gamestate:
    description: "Allows use of the /gamestate command"
    default: false
  mccw.cw:
    description: "Allows use of all subcommands of /cw"
    default: false
    children:
      mccw.cw.money: true
      mccw.cw.building: true
      mccw.cw.team: true
      mccw.cw.custom: true
  mccw.cw.money:
    description: "Allows use of /cw money"
    default: false
  mccw.cw.building:
    description: "Allows use of /cw building"
    default: false
  mccw.cw.team:
    description: "Allows use of /cw team"
    default: false
  mccw.cw.custom:
    description: "Allows use of /cw custom"
    default: false
  mccw.tmm:
    description: "Allows use of /tmm"
    default: false
  mccw.tmm.others:
    description: "Allows changing of money message status for others"
    default: false
  mccw.stats:
    description: "Allows use of /stats"
    default: false
  mccw.countdown:
    description: "Allows use of /countdown"
    default: false

commands:
  gamestate:
    description: "Changes the GameState of the current GameGroup"
    aliases: ["gs", "gstate"]
    permission: "mccw.gamestate"
    usage: "/<command> <gamestate>"
  colonywars:
    description: "Various CW testing utils"
    aliases: ["cw", "cwars", "wars"]
    usage: "/<command> <subcommand> [sub command args...]"
  togglemoneymessage:
    description: "Toggles money message status"
    aliases: ["tmm"]
    usage: "/<command> [newstatus]"
  stats:
    description: "Shows your stats"
    usage: "/<command> [category]"
  countdown:
    description: "Modifies countdowns"
    aliases: ["cdown", "cd", "cdwn"]
    usage: |
      /<command> add/set <amount>
      /<command> finish/cancel
      /<command> start <name> <seconds> <localestub>